### ISSUE TITLE
[BP-2126] Fatal error: Unsupported operand types: string + int (PHP 8.0)

### ISSUE THREAD

**Issue by remyjacobs-rf** [buckaroo-it/WooCommerce#133]
After updating a website to PHP 8.0, the plugin gives a fatal error after adding a product to the cart. The error is;

`PHP Fatal error: Uncaught TypeError: Unsupported operand types: string + int in /wp-content/plugins/wc-buckaroo-bpe-gateway/gateway-buckaroo.php:137`

I could fix this myself by replacing r:117 in the same file to;
`$fee = intval(str_replace("%", "", $fee));`

Does the plugin needs an update, or is there something else wrong that I am missing here?

Plugin version 3.5.0
WooCommerce version 7.0.1
WordPress version 6.1
PHP version 8.0

**Comment by Buckaroo-Rens** [comment]
Hi @remyjacobs-rf we are indeed aware of the new PrestaShop version (8.0) but there are still a lot of issues with it. Due to that we are not planning to fix support for it within the coming period. We will be first waiting for a more stable version of it (8.1). Also, it's a big release, a lot of thinks/logic has changed, so it will take a while for we will even be able to support it. 

Beside the support we are planning on doing a complete cleanup/refactor of our plugin. Better code, more functionality, more supported payment methods.

**Comment by remyjacobs-rf** [comment]
Hi @Buckaroo-Rens , I think you mixed up some things. It's about Wordpress/Woocommerce with PHP 8.0 , it has nothing to do with Prestashop.

**Comment by Buckaroo-Rens** [comment]
Your right, 2 Git tabs open does not work :) 

We are looking into the PHP error ;)

**Comment by Buckaroo-Rene** [comment]
@remyjacobs-rf ,
We just did a new release including a fix for the issue that you've had.
