### ISSUE TITLE
Order status payment complete not working

### ISSUE THREAD

**Issue by Coders91** [buckaroo-it/WooCommerce#239]
Hello,

I believe this is similar to the other open [issue](https://github.com/buckaroo-it/WooCommerce/issues/199) but since my decimal settings are stock, i decided to open a new issue. The problem is that orders fully paid with all payment methods never get the payment status completed. Other statuses like failed do work. Can we expect a fix?

**Comment by Buckaroo-Rene** [comment]
Hello @Coders91,

Thank you for contacting us.
Can you give me an transaction key from one of your recent transactions?
You can find this by logging in into the [Buckaroo Plaza](https://plaza.buckaroo.nl/a and then go to the transaction overview and click on the last transaction.

Then I can check if it isn't something with the PUSH messages in your connectopn because we don't experience the issue you are facing for orders not being updated.

Please let me know.

Best Regards,
René Licher

**Comment by Coders91** [comment]
60B0A9F575CC44259BBBE77CC5A4EFD5

I do see that the push has failed because no valid url was provided. What url are we talking about and where can i set this?

**Comment by Buckaroo-Rene** [comment]
@Coders91 ,
Please refer to the installation manual with the part about the PUSH messages:
https://docs.buckaroo.io/docs/woocommerce-configuration

I have already applied the changes and you should be able to get a proper update for the orders now.
With your website URL (https://[YOURWEBSITE].nl/?wc-api=WC_Push_Buckaroo

Best Regards,
René Licher

**Comment by Buckaroo-Rene** [comment]
@Coders91 ,

Please check your test order 11554.
That should have the correct status now.

Best Regards,
René

**Comment by Coders91** [comment]
@Buckaroo-Rene

It does seem to be working now, thank you for your help.
